### ISSUE TITLE
Keycloak v24+ compatibility

### ISSUE THREAD

**Issue by this-is-tobi** [codegouvfr/keycloak-theme-dsfr#13]
Hi, hope you're well !

Is it possible to have an approximate release date of the Keycloak `v24`, `v25` or `v26` compatible version ?

Thanks for this repo 🫶🏻

**Comment by garronej** [comment]
Hello @this-is-tobi,  

This is definitely something I want to do, especially since Keycloakify is now much more mature than when this theme was initially created.  
However, it's not a top priority for me at the moment because, aside from the great feedback I receive from the community through issues, there’s little acknowledgment or appreciation from DINUM or SIG for the work I’ve been doing, particularly around DSFR, like with [react-dsfr](https://github.com/codegouvfr/react-dsfr).  

I’m doing this purely out of goodwill, in addition to my existing responsibilities. I think it’s not clear to people that I don’t work at DINUM or for any DSFR-related site.  

That being said, I’ll get to it eventually, but I have more pressing matters to attend to right now.  

I hope you understand.

**Comment by this-is-tobi** [comment]
It's a pity that the DSFR or DINUM teams haven't shown more interest in your work. 

I fully understand that this is not a priority for you, and that you are already actively working on a number of repositories (thank you for the developments requested by Thierry Gameiro on Onyxia).
I'll wait until you find the time / I'll see if I can find the time to make a proposal (:
